### ISSUE TITLE
Issue With Height Blink

### ISSUE THREAD

**Issue by tulsiojha** [abdheshnayak/react-pulsable#1]
**Describe the bug**
While going into loading mode the height of component is slightly increased.

**Expected behavior**
Component height and width should be same always. (before and while loading).

**Comment by abdheshnayak** [comment]
[fixed-with-this-commit](https://github.com/OpenSource-HQ/react-pulsable/commit/1c0e0eda5a0649ceeb6773769243742d11cbbb6e)
